/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false backend/src/worker-env.d.ts` (hash: cbf69cf0e5a006ddbcba6a51b847ff80)
interface __BaseEnv_Env {
	DB: D1Database;
	XUGOU_JOBS: Queue;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	FREE_MODE: string;
	AGENT_ENROLLMENT_TTL_MINUTES: string;
	NOTIFICATION_KEK_VERSION: string;
	NOTIFICATION_KEK_ROTATION_ENABLED: string;
	MIN_AGENT_REPORT_INTERVAL_SECONDS: string;
	MIN_MONITOR_INTERVAL_SECONDS: string;
	MONITOR_CHECK_BATCH_SIZE: string;
	MONITOR_SCHEDULER_TIME_BUDGET_MS: string;
	AGENT_OFFLINE_BATCH_SIZE: string;
	STATUS_PAGE_CACHE_TTL_SECONDS: string;
	PUBLIC_METRICS_CACHE_TTL_SECONDS: string;
	AGENT_ROLLUP_RETENTION_DAYS: string;
	MONITOR_ROLLUP_RETENTION_DAYS: string;
	AGENT_REPORT_RETENTION_DAYS: string;
	MONITOR_SAMPLE_RETENTION_DAYS: string;
	MONITOR_DAILY_ROLLUP_RETENTION_DAYS: string;
	MONITOR_INCIDENT_RETENTION_DAYS: string;
	SECURITY_AUDIT_RETENTION_DAYS: string;
	STATUS_PUBLICATION_RETENTION_DAYS: string;
	PROCESSED_EVENT_RETENTION_DAYS: string;
	NOTIFICATION_EVENT_RETENTION_DAYS: string;
	LATEST_AGENT_VERSION: string;
	AGENT_ROOM: DurableObjectNamespace<import("./index").AgentRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgentRoom";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FREE_MODE" | "AGENT_ENROLLMENT_TTL_MINUTES" | "NOTIFICATION_KEK_VERSION" | "NOTIFICATION_KEK_ROTATION_ENABLED" | "MIN_AGENT_REPORT_INTERVAL_SECONDS" | "MIN_MONITOR_INTERVAL_SECONDS" | "MONITOR_CHECK_BATCH_SIZE" | "MONITOR_SCHEDULER_TIME_BUDGET_MS" | "AGENT_OFFLINE_BATCH_SIZE" | "STATUS_PAGE_CACHE_TTL_SECONDS" | "PUBLIC_METRICS_CACHE_TTL_SECONDS" | "AGENT_ROLLUP_RETENTION_DAYS" | "MONITOR_ROLLUP_RETENTION_DAYS" | "AGENT_REPORT_RETENTION_DAYS" | "MONITOR_SAMPLE_RETENTION_DAYS" | "MONITOR_DAILY_ROLLUP_RETENTION_DAYS" | "MONITOR_INCIDENT_RETENTION_DAYS" | "SECURITY_AUDIT_RETENTION_DAYS" | "STATUS_PUBLICATION_RETENTION_DAYS" | "PROCESSED_EVENT_RETENTION_DAYS" | "NOTIFICATION_EVENT_RETENTION_DAYS" | "LATEST_AGENT_VERSION">> {}
}
